export const addresses = {
  "": [],
  "Yangon (ရန်ကုန်တိုင်း)": [
    "Botataung (ဗိုလ်တထောင်)",
    "Dagon Seikkan (ဒဂုံဆိပ်ကမ်း)",
    "East Dagon (အရှေ့ဒဂုံ)",
    "North Dagon (မြောက်ဒဂုံ)",
    "South Dagon (တောင်ဒဂုံ)",
    "North Okkalapa (မြောက်ဥက္ကလာပ)",
    "South Okkalapa (တောင်ဥက္ကလာပ)",
    "Pazundaung (ပုဇွန်တောင်)",
    "Thingangyun (သင်္ဃန်းကျွန်း)",
    "Dawbon (ဒေါပုံ)",
    "Mingalar Taungnyunt (မင်္ဂလာတောင်ညွှန့်)",
    "Tamwe (တာမွေ)",
    "Thaketa (သာကေတ)",
    "Yankin (ရန်ကင်း)",
    "Hlaing Tharyar (လှိုင်သာယာ)",
    "Insein (အင်းစိန်)",
    "Mingalardon (မင်္ဂလာဒုံ)",
    "Shwepyitha (ရွှေပြည်သာ)",
    "Hlegu (လှည်းကူး)",
    "Hmawbi (မှော်ဘီ)",
    "Htantabin (ထန်းတပင်)",
    "Taikkyi (တိုက်ကြီး)",
    "Dala (ဒလ)",
    "Seikkyi Kanaungto (ဆိပ်ကြီးခနောင်တို)",
    "Cocokyun (ကိုကိုးကျွန်း)",
    "Kawhmu (ကော့မှူး)",
    "Kayan (ခရမ်း)",
    "Kungyangon (ကွမ်းခြံကုန်း)",
    "Kyauktan (ကျောက်တန်း)",
    "Thanlyi (သန်လျင်)",
    "Thongwa (သုံးခွ)",
    "Thonse (သုံးဆယ်)",
    "Twante (တွံတေး)",
    "Ahlon (အလုံ)",
    "Bahan (ဗဟန်း)",
    "Dagon (ဒဂုံ)",
    "Kyauktada (ကျောက်တံတား)",
    "Kyimyindaing (ကြည့်မြင်တိုင်)",
    "Lanmadaw (လမ်းမတော်)",
    "Latha (လသာ)",
    "Pabedan (ပန်းပဲတန်း)",
    "Sanchaung (စမ်းချောင်း)",
    "Seikkan (ဆိပ်ကမ်း)",
    "Hlaing (လှိုင်)",
    "Kamayut (ကမာရွတ်)",
    "Mayangon (မရမ်းကုန်း)",
  ],
  "Mandalay (မန္တလေးတိုင်း)": [
    "Kyaukse (ကျောက်ဆည်မြို့)",
    "Taungtha (တောင်သာ)",
    "Mandalay (မန္တလေးမြို့)",
    "Myittha (မြစ်သားမြို့)",
    "Sintgaing (စဉ့်ကိုင်)",
    "Tada_U (တံတားဦး)",
    "Amarapura (အမရပူရ)",
    "Aungmyethazan (အောင်မြေသာစံ)",
    "Chanayethazan (ချမ်းအေးသာစံ)",
    "Chanmyathazi (ချမ်းမြသာစည်)",
    "Mahaaungmye (မဟာအောင်မြေ)",
    "Patheingyi (ပုသိမ်ကြီး)",
    "Pyigyidagun (ပြည်ကြီးတံခွန်)",
    "Mahlaing (မလှိုင်)",
    "Meiktila (မိတ္ထီလာ)",
    "Thazi (သာစည်)",
    "Wundwin (ဝမ်းတွင်း)",
    "Myingyan (မြင်းခြံ)",
    "Natogyi (နွားထိုးကြီး)",
    "Nganzun (ငါန်းဇွန်)",
    "Thaungtha (တောင်သာ)",
    "Nyaung-U (ညောင်ဦး)",
    "Kyaukpadaung (ကျောက်ပန်းတောင်း)",
    "Ngathayauk (ငါ့သရောက်)",
    "Madaya (မတ္တရာ)",
    "Mogok (မိုးကုတ်)",
    "Pyinoolwin (ပြင်ဦးလွင်)",
    "Singu (စဉ့်ကူ)",
    "Thabeikkyin (သပိတ်ကျင်း)",
    "Tagaung (တကောင်း)",
    "Pyawbwe (ပျော်ဘွယ်)",
    "Yamethin (ရမည်းသင်း)",
  ],
  "Magway (မကွေးတိုင်း)": [
    "Gangaw (ဂန့်ဂေါ)",
    "Myit Chay (မြစ်ခြေ)",
    "Saw (စော)",
    "Tilin (ထီးလင်း)",
    "Chauck (ချောက်)",
    "Magway (မကွေးမြို့)",
    "Natmauk (နတ်မောက်)",
    "Taungdwingyi (တောင်တွင်းကြီး)",
    "Yenangyaung (ရေနံချောင်း)",
    "Minbu (မင်းဘူး)",
    "Ngape (ငဖဲ)",
    "Pwintbyu (ပွင့်ဖြူ)",
    "Salin (စလင်း)",
    "Myaing (မြိုင်)",
    "Pakokku (ပခုက္ကူ)",
    "Pauk (ပေါက်)",
    "Seikphyu (ဆိပ်ဖြူ)",
    "Yesagyo (ရေစကြို)",
    "Aunglan (အောင်လံ)",
    "Kamma (ကမ္မ)",
    "Mindon (မင်းတုန်း)",
    "Minhla (မင်းလှ)",
    "Sinbaungwe (ဆင်ပေါင်ဝဲ)",
    "Thayet (သရက်)",
  ],
  "Naypyidaw (နေပြည်တော်)": [
    "Thar Wut Hti (သာဝတ်ထိ)",
    "Dekkhinathiri (ဒက္ခိဏသီရိ)",
    "Lewe (လယ်ဝေး)",
    "Pyinmana (ပျဉ်းမနား)",
    "Zabuthiri (ဇမ္မူသီရိ)",
    "Naypyidaw (နေပြည်တော်)",
    "Ottarathiri (ဥတ္တရသီရိ)",
    "Pobbathiri (ပုပ္ဗသီရိ)",
    "Tatkon (တပ်ကုန်း)",
    "Zeyarthiri (ဇေယျာသီရိ)",
  ],
  "Ayeyarwady (ဧရာဝတီတိုင်း)": [
    "Yegyi (ရေကြည်)",
    "Myaungmya (မြောင်းမြ)",
    "Hinthada (ဟင်္သာတ)",
    "Lemyethna (လေးမျက်နှာ)",
    "Zalun (ဇလွန်)",
    "Ingapu (အင်္ဂပူ)",
    "Kyangin (ကြံခင်း)",
    "Myanaung (မြောင်းမြ)",
    "Labutta (လပွတ္တာ)",
    "Mawlamyinegyun (မော်လမြိုင်ကျွန်း)",
    "Pyinsalu (ပြင်စလူခွဲ)",
    "Danuphyu (ဓနုဖြူ)",
    "Ma-ubin (မအူပင်)",
    "Nyaungdon (ညောင်တုန်း)",
    "Pantanaw (ပန်းတနော်)",
    "Einme (အိမ်မဲ)",
    "Wakema (ဝါးခယ်မ)",
    "Kangyidaunk (ကန်ကြီးတောင့်)",
    "Ngapudaw (ငပုတော)",
    "Pathein (ပုသိမ်မြို့)",
    "Thabaung (သာပေါင်း)",
    "Kyaunggon (ကျောင်းကုန်း)",
    "Kyonpyaw (ကျုံပျော်)",
    "Yekyi (ရေကြီး)",
    "Ngayokaung (ငရုပ်ကောင်း)",
    "Hainggyikyun (ဟိုင်းကြီးကျွန်း)",
    "Shwethaungyan (ရွှေသာယန်ကျေးရွာအုပ်ချုပ်ရေးမှူး)",
    "Ngwehsaung (ငွေဆောင်)",
    "Chaungthar (ချောင်းသာ)",
    "Ngathaingchaung (ငသိုင်းချောင်းခွဲ)",
    "Bogale (ဘိုကလေး)",
    "Dedaye (ဒေးဒရဲ)",
    "Kyaiklat (ကျိုက်လတ်)",
    "Pyapon (ဖျာပုံ)",
    "Ahmar (အမာခွဲ)",
  ],
  "Bago (ပဲခူးတိုင်း)": [
    "Thar Ga Ya (သာဂရ)",
    "Bago (ပဲခူး)",
    "Daik-U (ဒိုက်ဦး)",
    "Kawa (ကဝ)",
    "Nyaunglebin (ညောင်လေးပင်)",
    "Shwegyin (ရွှေကျင်)",
    "Thanatpin (သနပ္်ပင်)",
    "Waw (ဝေါ)",
    "Kyauktaga (ကျောက်တံခါး)",
    "Hpayargyi (ဘုရားကြီး)",
    "Pyuntaza (ပြွန်တန်ဆာခွဲ)",
    "Madauk (မဒေါက်)",
    "Penwegon (ပဲနွယ်ကုန်းခွဲ)",
    "Aungmyin (အောင်မြေ)",
    "Kyaukkyi (ကျောက်ကြီး)",
    "Oktwin (အုတ်တွင်း)",
    "Pyu (ပျူ)",
    "Tantabin (ထန်းတပင်)",
    "Taungoo (တောင်ငူ)",
    "Yedashe (ရေတာရှည်)",
    "Kanyutkwin (ကညွတ်ကွင်း)",
    "Nyaungbinthar (ညောင်ပင်သာ)",
    "Kywebwe (ကျွဲပွဲ)",
    "Padaung (ပန်းတောင်း)",
    "Paukkaung (ပေါက်ခေါင်း)",
    "Paungde (ပေါင်းတည်)",
    "Pyay (ပြည်)",
    "Shwedaung (ရွှေတောင်)",
    "Thegon (သဲကုန်း)",
    "Innma (အင်းမ)",
    "Padigone (ပုတီးကုန်း)",
    "Sinmezwe (ဆင်မြီးဆွဲ)",
    "Paungdale (ပေါင်းတလည်)",
    "Gyobingauk (ကြို့ပင်ကောက်)",
    "Letpadan (လက်ပတန်းမြို့)",
    "Minhla (မင်းလှ)",
    "Monyo (မိုးညို)",
    "Okpho (အုတ်ဖို)",
    "Tharrawaddy (သာရ၀တီ)",
    "Nattalin (နတ်တလင်း)",
    "Zigon (ဇီးကုန်း)",
    "Thonze (သုံးဆယ်)",
    "Ooethegone (အိုးသည်ကုန်း)",
    "Sitkwin (စစ်ကွင်း)",
    "Tapun (တာပွန်)",
  ],
  "Sagaing (စစ်ကိုင်းတိုင်း)": [
    "Hkamti (ခန္တီး)",
    "Homalin (ဟုမ္မလင်း)",
    "Leshi (လေရှီး)",
    "Nanyun (နန်းယွန်း)",
    "Donhee (ဒုံဟီး)",
    "Htanparkway (ထန်ပါခွေ)",
    "Pansaung (ပန်ဆောင်)",
    "Kanbalu (ကန့်ဘလူ)",
    "Kyunhla (ကျွန်းလှ)",
    "Taze (တန့်ဆည်)",
    "Ye-U (ရေဦး)",
    "Kale (ကလေး)",
    "Kalewa (ကလေးဝ)",
    "Mingin (မင်းကင်း)",
    "Banmauk (ဗန်းမောက်)",
    "Indaw (အင်းတော်)",
    "Katha (ကသာ)",
    "Kawlin (ကောလင်)",
    "Pinlebu (ပင်လည်ဘူး)",
    "Tigyaing (ထီးချိုင့်)",
    "Wuntho (ဝန်းသို)",
    "Mawlaik (မော်လိုက်)",
    "Paungbyin (ဖေါင်းပြင်)",
    "Ayadaw (အရာတော်)",
    "Budalin (ဘုတလင်)",
    "Chaung-U (ချောင်းဦး)",
    "Monywa (မုံရွာ)",
    "Myaung (မြှောင်)",
    "Myinmu (မြင်းမူ)",
    "Sagaing (စစ်ကိုင်း)",
    "Khin-U (ခင်ဦး)",
    "Shwebo (ရွှေဘို)",
    "Wetlet (ဝက်လက်)",
    "Tabayin (ဒီပဲယင်း)",
    "Kyaukmyaung (ကျောက်မြောင်း)",
    "Tamu (တမူး)",
    "Khampat (ခန်းပတ်)",
    "Myothit (မြို့သစ်)",
    "Kani (ကနီ)",
    "Pale (ပုလဲ)",
    "Salingyi (ဆားလင်းကြီး)",
    "Yinmabin (ယင်းမာပင်)",
  ],
  "Tanintharyi (တနင်္သာရီတိုင်း)": [
    "Dawei (ထားဝယ်)",
    "Launglon (လောင်းလုံ)",
    "Thayetchaung (သရက်ချောင်း)",
    "Yebyu (ရေဖြူ)",
    "Kaleinaung (ကလိန်အောင်)",
    "Myitta (မေတ္တာ)",
    "Bokpyin (ဘုတ်ပြင်း)",
    "Kawthoung (ကော့သောင်း)",
    "Karathuri (ကရသူရိ)",
    "Khamaukgyi (ခမောက်ကြီး)",
    "Pyigyimandaing (ပြည်ကြီးမဏ္ဍိုင်)",
    "Kyunsu (ကျွန်းစု)",
    "Myeik (မြိတ်)",
    "Palaw (ပုလော)",
    "Palauk (ပလောက်)",
  ],
  "East Shan State (အရှေ့ရှမ်းပြည်နယ်)": [
    "Kengtung (ကျိုင်းတုံ)",
    "Mong Khet (မိုင်းခတ်)",
    "Mong La (မိုင်းလား)",
    "Mong Yang (မိုင်းယန်း)",
    "Mine Pauk (မိုင်းပေါက်)",
    "Mong Hpayak (မိုင်းဖြတ်)",
    "Mong Yawng (မိုင်းယောင်း)",
    "Mong Hsat (မိုင်းဆတ်)",
    "Mong Ping (မိုင်းပြင်း)",
    "Mong Tong (မိုင်းတုံ)",
    "Tachileik (တာချီလိတ်)",
    "Minekoke (မိုင်းကုတ်)",
    "Ponparkyin (ပုံပါကျင်)",
  ],
  "North Shan State (ရှမ်းပြည်နယ်မြောက်ပိုင်း )": [
    "Hsipaw (သီပေါ)",
    "Kyaukme (ကျောက်မဲ)",
    "Mantong (မန်တုန်)",
    "Namhsan (နမ့်ဆန်)",
    "Namtu (နမ္မတူ)",
    "Nawnghkio (နောင်ချို)",
    "Hsenwi (သိန္နီ)",
    "Lashio (လားရှိုး)",
    "Mongyai (မိုင်းရယ်)",
    "Tangyan (တန့်ယန်း)",
    "Laukkaing (လောက်ကိုင်)",
    "Konkyan (ကုန်းကြမ်း)",
    "Kutkai (ကွတ်ခိုင်)",
    "Muse (မူဆယ်)",
    "Namhkam (နမ့်ခမ်း)",
    "Hopang (ဟိုပုန်)",
    "Mongmao (မိုင်းမော)",
    "Pangwaun (ပန်ဝိုင်)",
    "Matman (မက်မန်း)",
    "Pangsang (ပန်ဆန်း)",
    "Mabein (မဘိမ်း)",
    "Mongmit (မိုးမိတ်)",
  ],
  "South Shan State (တောင်ပိုင်းရှမ်းပြည်နယ်)": [
    "Langkho (လင်းခေး)",
    "Mawkmai (မောက်မယ်)",
    "Mong Nai (မိုင်းနိုင်း)",
    "Mong Pan (မိုင်းပန်)",
    "Kunhing (ကွန်ဟိန်း)",
    "Kyethi (ကျေးသီး)",
    "Lai-Hka (လဲချား)",
    "Loilen (လွိုင်လင်)",
    "Mong Hsu (မိုင်းရှူး)",
    "Mong Kung (မိုင်းကိုင်)",
    "Nansang (နမ့်စန်)",
    "Hopong (ဟိုပုံး)",
    "Hsi Hseng (ဆီဆိုင်)",
    "Kalaw (ကလော)",
    "Lawksawk (ရပ်စောက်)",
    "Nyaungshwe (ညောင်ရွှေ)",
    "Pekon (ဖယ်ခုံ)",
    "Pingdaya (ပင်းတယ)",
    "Pinlaung (ပင်လောင်း)",
    "Taunggyi (တောင်ကြီး)",
    "Ywangan (ရှာငံ)",
  ],
  "Kachin State (ကချင်ပြည်နယ်)": [
    "Bhamo (ဗန်းမော်)",
    "Mansi (မန်စီ)",
    "Momauk (မိုးမောက်)",
    "Shwegu (ရွှေကူ)",
    "Hpakant (ဖားကန့်)",
    "Mogaung (မိုးကောင်း)",
    "Mohnyin (မိုးညှင်း)",
    "Chipwi (ချီဗွေ)",
    "Hsawlaw (ဆော့လော)",
    "Injangyang (အင်ဂျန်းယန်)",
    "Myitkyina (မြစ်ကြီးနားမြို့)",
    "Tanai (တနိုင်း)",
    "Waingmaw (ဝိုင်းမော်)",
    "Kawnglanghpu (ခေါင်လန်ဖူး)",
    "Machanbaw (မချမ်းဘေ)",
    "Nogmung (နောင်မွန်း)",
    "Puta-O (ပူတာအို)",
    "Sumprabum (ဆွမ်ပရာဘွမ်)",
  ],
  "Kayin State (ကရင်ပြည်နယ်)": [
    "Hlaignbwe (လှိုင်ဘွဲ့)",
    "Hpa-an (ဘားအံ)",
    "Thandaunggyi (သံတောင်ကြီး)",
    "Hpapun (ဖာပွန်)",
    "Kawkareik (ကော့ကရိတ်)",
    "Kyain Seikgyi (ကြာအင်းဆိပ်ကြီး)",
    "Myawaddy (မြဝတီ)",
  ],
  "Mon State (မွန်ပြည်နယ်)": [
    "Chaungzon (ချောင်းဆုံ)",
    "Kyaikmaraw (ကျိုက်မရော)",
    "Mawlamyine (မော်လမြိုင်)",
    "Mudon (မုဒုံ)",
    "Thanbyuzayat (သံဖြူဇရပ်)",
    "Ye (ရေး)",
    "Bilin (ဘီလင်း)",
    "Kyaikto (ကျိုက်ထို)",
    "Paung (ပေါင်)",
    "Thaton (သထုံ)",
  ],
  "Chin State (ချင်းပြည်နယ်)": [
    "Falam (ဖလမ်း)",
    "Tiddim (တီးတိန်)",
    "Ton Zang (တွန်းဇံ)",
    "Hakha (ဟားခါး)",
    "Htantlang (ထန်တလန်)",
    "Kanpetlet (ကန်ပက်လက်)",
    "Matupi (မတူပီ)",
    "Mindat (မင်းတပ်)",
    "Paletwa (ပလက်၀)",
  ],
  "Rakhine State (ရခိုင်ပြည်နယ်)": [
    "Ann (အမ်း)",
    "Kyaukpyu (ကျောက်ဖြူ)",
    "Manaung (မာန်အောင်)",
    "Ramree (ရမ်းဗြဲ)",
    "Buthidaung (ဘူးသီးတောင်)",
    "Maungdaw (မောင်တော)",
    "Pauktaw (ပေါက်တော)",
    "Ponnagyun (ပုဏ္ဏားကျွန်း)",
    "Rathedaung (ရသေ့တောင်)",
    "Sittwe (စစ်တွေ)",
    "Gaw (ဂေါ)",
    "Thandwe (သံတွဲ)",
    "Toungup (တောင်ကုတ်)",
    "Kyauktaw (ကျောက်တော်)",
    "Minbya (မင်းပြား)",
    "Mrauk-U (မြောက်ဦး)",
    "Myebon (မြေပုံ)",
  ],
  "Kayah State (ကယားပြည်နယ်)": [
    "Bawlakhe (ဘောလခဲ)",
    "Hpasawng (ဖားဆောင်း)",
    "Mese (မယ်ဆည်)",
    "Demoso (ဒီမောဆို)",
    "Hpruso (ဖရူဆို)",
    "Loikaw (လွိုင်ကော်)",
    "Shadaw (ရှားတော)",
  ],
};
