export type states =
  | "Yangon_(ရန်ကုန်တိုင်း)"
  | "Mandalay_(မန္တလေးတိုင်း)"
  | "Magway_(မကွေးတိုင်း)"
  | "Naypyidaw_(နေပြည်တော်)"
  | "Ayeyarwady_(ဧရာဝတီတိုင်း)"
  | "Bago_(ပဲခူးတိုင်း)"
  | "Sagaing_(စစ်ကိုင်းတိုင်း)"
  | "Tanintharyi_(တနင်္သာရီတိုင်း)"
  | "East_Shan_State_(အရှေ့ရှမ်းပြည်နယ်)"
  | "North_Shan_State_(ရှမ်းပြည်နယ်မြောက်ပိုင်း)"
  | "South_Shan_State_(တောင်ပိုင်းရှမ်းပြည်နယ်)"
  | "Kachin_State_(ကချင်ပြည်နယ်)"
  | "Kayin_State_(ကရင်ပြည်နယ်)"
  | "Mon_State_(မွန်ပြည်နယ်)"
  | "Chin_State_(ချင်းပြည်နယ်)"
  | "Rakhine_State_(ရခိုင်ပြည်နယ်)"
  | "Kayah_State_(ကယားပြည်နယ်)"
  | "";
export const states: states[] = [
  "Yangon_(ရန်ကုန်တိုင်း)",
  "Mandalay_(မန္တလေးတိုင်း)",
  "Magway_(မကွေးတိုင်း)",
  "Naypyidaw_(နေပြည်တော်)",
  "Ayeyarwady_(ဧရာဝတီတိုင်း)",
  "Bago_(ပဲခူးတိုင်း)",
  "Sagaing_(စစ်ကိုင်းတိုင်း)",
  "Tanintharyi_(တနင်္သာရီတိုင်း)",
  "East_Shan_State_(အရှေ့ရှမ်းပြည်နယ်)",
  "North_Shan_State_(ရှမ်းပြည်နယ်မြောက်ပိုင်း)",
  "South_Shan_State_(တောင်ပိုင်းရှမ်းပြည်နယ်)",
  "Kachin_State_(ကချင်ပြည်နယ်)",
  "Kayin_State_(ကရင်ပြည်နယ်)",
  "Mon_State_(မွန်ပြည်နယ်)",
  "Chin_State_(ချင်းပြည်နယ်)",
  "Rakhine_State_(ရခိုင်ပြည်နယ်)",
  "Kayah_State_(ကယားပြည်နယ်)",
  "",
];
export type cities = {
  "Yangon_(ရန်ကုန်တိုင်း)": string[];
  "Mandalay_(မန္တလေးတိုင်း)": string[];
  "Magway_(မကွေးတိုင်း)": string[];
  "Naypyidaw_(နေပြည်တော်)": string[];
  "Ayeyarwady_(ဧရာဝတီတိုင်း)": string[];
  "Bago_(ပဲခူးတိုင်း)": string[];
  "Sagaing_(စစ်ကိုင်းတိုင်း)": string[];
  "Tanintharyi_(တနင်္သာရီတိုင်း)": string[];
  "East_Shan_State_(အရှေ့ရှမ်းပြည်နယ်)": string[];
  "North_Shan_State_(ရှမ်းပြည်နယ်မြောက်ပိုင်း)": string[];
  "South_Shan_State_(တောင်ပိုင်းရှမ်းပြည်နယ်)": string[];
  "Kachin_State_(ကချင်ပြည်နယ်)": string[];
  "Kayin_State_(ကရင်ပြည်နယ်)": string[];
  "Mon_State_(မွန်ပြည်နယ်)": string[];
  "Chin_State_(ချင်းပြည်နယ်)": string[];
  "Rakhine_State_(ရခိုင်ပြည်နယ်)": string[];
  "Kayah_State_(ကယားပြည်နယ်)": string[];
  "": string[];
};
export const cities: cities = {
  "": [],
  "Yangon_(ရန်ကုန်တိုင်း)": [
    "Botataung_(ဗိုလ်တထောင်)",
    "Dagon_Seikkan_(ဒဂုံဆိပ်ကမ်း)",
    "East_Dagon_(အရှေ့ဒဂုံ)",
    "North_Dagon_(မြောက်ဒဂုံ)",
    "South_Dagon_(တောင်ဒဂုံ)",
    "North_Okkalapa_(မြောက်ဥက္ကလာပ)",
    "South_Okkalapa_(တောင်ဥက္ကလာပ)",
    "Pazundaung_(ပုဇွန်တောင်)",
    "Thingangyun_(သင်္ဃန်းကျွန်း)",
    "Dawbon_(ဒေါပုံ)",
    "Mingalar_Taungnyunt_(မင်္ဂလာတောင်ညွှန့်)",
    "Tamwe_(တာမွေ)",
    "Thaketa_(သာကေတ)",
    "Yankin_(ရန်ကင်း)",
    "Hlaing_Tharyar_(လှိုင်သာယာ)",
    "Insein_(အင်းစိန်)",
    "Mingalardon_(မင်္ဂလာဒုံ)",
    "Shwepyitha_(ရွှေပြည်သာ)",
    "Hlegu_(လှည်းကူး)",
    "Hmawbi_(မှော်ဘီ)",
    "Htantabin_(ထန်းတပင်)",
    "Taikkyi_(တိုက်ကြီး)",
    "Dala_(ဒလ)",
    "Seikkyi_Kanaungto_(ဆိပ်ကြီးခနောင်တို)",
    "Cocokyun_(ကိုကိုးကျွန်း)",
    "Kawhmu_(ကော့မှူး)",
    "Kayan_(ခရမ်း)",
    "Kungyangon_(ကွမ်းခြံကုန်း)",
    "Kyauktan_(ကျောက်တန်း)",
    "Thanlyi_(သန်လျင်)",
    "Thongwa_(သုံးခွ)",
    "Thonse_(သုံးဆယ်)",
    "Twante_(တွံတေး)",
    "Ahlon_(အလုံ)",
    "Bahan_(ဗဟန်း)",
    "Dagon_(ဒဂုံ)",
    "Kyauktada_(ကျောက်တံတား)",
    "Kyimyindaing_(ကြည့်မြင်တိုင်)",
    "Lanmadaw_(လမ်းမတော်)",
    "Latha_(လသာ)",
    "Pabedan_(ပန်းပဲတန်း)",
    "Sanchaung_(စမ်းချောင်း)",
    "Seikkan_(ဆိပ်ကမ်း)",
    "Hlaing_(လှိုင်)",
    "Kamayut_(ကမာရွတ်)",
    "Mayangon_(မရမ်းကုန်း)",
  ],
  "Mandalay_(မန္တလေးတိုင်း)": [
    "Kyaukse_(ကျောက်ဆည်မြို့)",
    "Taungtha_(တောင်သာ)",
    "Mandalay_(မန္တလေးမြို့)",
    "Myittha_(မြစ်သားမြို့)",
    "Sintgaing_(စဉ့်ကိုင်)",
    "Tada_U_(တံတားဦး)",
    "Amarapura_(အမရပူရ)",
    "Aungmyethazan_(အောင်မြေသာစံ)",
    "Chanayethazan_(ချမ်းအေးသာစံ)",
    "Chanmyathazi_(ချမ်းမြသာစည်)",
    "Mahaaungmye_(မဟာအောင်မြေ)",
    "Patheingyi_(ပုသိမ်ကြီး)",
    "Pyigyidagun_(ပြည်ကြီးတံခွန်)",
    "Mahlaing_(မလှိုင်)",
    "Meiktila_(မိတ္ထီလာ)",
    "Thazi_(သာစည်)",
    "Wundwin_(ဝမ်းတွင်း)",
    "Myingyan_(မြင်းခြံ)",
    "Natogyi_(နွားထိုးကြီး)",
    "Nganzun_(ငါန်းဇွန်)",
    "Thaungtha_(တောင်သာ)",
    "Nyaung-U_(ညောင်ဦး)",
    "Kyaukpadaung_(ကျောက်ပန်းတောင်း)",
    "Ngathayauk_(ငါ့သရောက်)",
    "Madaya_(မတ္တရာ)",
    "Mogok_(မိုးကုတ်)",
    "Pyinoolwin_(ပြင်ဦးလွင်)",
    "Singu_(စဉ့်ကူ)",
    "Thabeikkyin_(သပိတ်ကျင်း)",
    "Tagaung_(တကောင်း)",
    "Pyawbwe_(ပျော်ဘွယ်)",
    "Yamethin_(ရမည်းသင်း)",
  ],
  "Magway_(မကွေးတိုင်း)": [
    "Gangaw_(ဂန့်ဂေါ)",
    "Myit_Chay_(မြစ်ခြေ)",
    "Saw_(စော)",
    "Tilin_(ထီးလင်း)",
    "Chauck_(ချောက်)",
    "Magway_(မကွေးမြို့)",
    "Natmauk_(နတ်မောက်)",
    "Taungdwingyi_(တောင်တွင်းကြီး)",
    "Yenangyaung_(ရေနံချောင်း)",
    "Minbu_(မင်းဘူး)",
    "Ngape_(ငဖဲ)",
    "Pwintbyu_(ပွင့်ဖြူ)",
    "Salin_(စလင်း)",
    "Myaing_(မြိုင်)",
    "Pakokku_(ပခုက္ကူ)",
    "Pauk_(ပေါက်)",
    "Seikphyu_(ဆိပ်ဖြူ)",
    "Yesagyo_(ရေစကြို)",
    "Aunglan_(အောင်လံ)",
    "Kamma_(ကမ္မ)",
    "Mindon_(မင်းတုန်း)",
    "Minhla_(မင်းလှ)",
    "Sinbaungwe_(ဆင်ပေါင်ဝဲ)",
    "Thayet_(သရက်)",
  ],
  "Naypyidaw_(နေပြည်တော်)": [
    "Thar_Wut_Hti_(သာဝတ်ထိ)",
    "Dekkhinathiri_(ဒက္ခိဏသီရိ)",
    "Lewe_(လယ်ဝေး)",
    "Pyinmana_(ပျဉ်းမနား)",
    "Zabuthiri_(ဇမ္မူသီရိ)",
    "Naypyidaw_(နေပြည်တော်)",
    "Ottarathiri_(ဥတ္တရသီရိ)",
    "Pobbathiri_(ပုပ္ဗသီရိ)",
    "Tatkon_(တပ်ကုန်း)",
    "Zeyarthiri_(ဇေယျာသီရိ)",
  ],
  "Ayeyarwady_(ဧရာဝတီတိုင်း)": [
    "Yegyi_(ရေကြည်)",
    "Myaungmya_(မြောင်းမြ)",
    "Hinthada_(ဟင်္သာတ)",
    "Lemyethna_(လေးမျက်နှာ)",
    "Zalun_(ဇလွန်)",
    "Ingapu_(အင်္ဂပူ)",
    "Kyangin_(ကြံခင်း)",
    "Myanaung_(မြောင်းမြ)",
    "Labutta_(လပွတ္တာ)",
    "Mawlamyinegyun_(မော်လမြိုင်ကျွန်း)",
    "Pyinsalu_(ပြင်စလူခွဲ)",
    "Danuphyu_(ဓနုဖြူ)",
    "Ma-ubin_(မအူပင်)",
    "Nyaungdon_(ညောင်တုန်း)",
    "Pantanaw_(ပန်းတနော်)",
    "Einme_(အိမ်မဲ)",
    "Wakema_(ဝါးခယ်မ)",
    "Kangyidaunk_(ကန်ကြီးတောင့်)",
    "Ngapudaw_(ငပုတော)",
    "Pathein_(ပုသိမ်မြို့)",
    "Thabaung_(သာပေါင်း)",
    "Kyaunggon_(ကျောင်းကုန်း)",
    "Kyonpyaw_(ကျုံပျော်)",
    "Yekyi_(ရေကြီး)",
    "Ngayokaung_(ငရုပ်ကောင်း)",
    "Hainggyikyun_(ဟိုင်းကြီးကျွန်း)",
    "Shwethaungyan_(ရွှေသာယန်ကျေးရွာအုပ်ချုပ်ရေးမှူး)",
    "Ngwehsaung_(ငွေဆောင်)",
    "Chaungthar_(ချောင်းသာ)",
    "Ngathaingchaung_(ငသိုင်းချောင်းခွဲ)",
    "Bogale_(ဘိုကလေး)",
    "Dedaye_(ဒေးဒရဲ)",
    "Kyaiklat_(ကျိုက်လတ်)",
    "Pyapon_(ဖျာပုံ)",
    "Ahmar_(အမာခွဲ)",
  ],
  "Bago_(ပဲခူးတိုင်း)": [
    "Thar_Ga_Ya_(သာဂရ)",
    "Bago_(ပဲခူး)",
    "Daik-U_(ဒိုက်ဦး)",
    "Kawa_(ကဝ)",
    "Nyaunglebin_(ညောင်လေးပင်)",
    "Shwegyin_(ရွှေကျင်)",
    "Thanatpin_(သနပ္်ပင်)",
    "Waw_(ဝေါ)",
    "Kyauktaga_(ကျောက်တံခါး)",
    "Hpayargyi_(ဘုရားကြီး)",
    "Pyuntaza_(ပြွန်တန်ဆာခွဲ)",
    "Madauk_(မဒေါက်)",
    "Penwegon_(ပဲနွယ်ကုန်းခွဲ)",
    "Aungmyin_(အောင်မြေ)",
    "Kyaukkyi_(ကျောက်ကြီး)",
    "Oktwin_(အုတ်တွင်း)",
    "Pyu_(ပျူ)",
    "Tantabin_(ထန်းတပင်)",
    "Taungoo_(တောင်ငူ)",
    "Yedashe_(ရေတာရှည်)",
    "Kanyutkwin_(ကညွတ်ကွင်း)",
    "Nyaungbinthar_(ညောင်ပင်သာ)",
    "Kywebwe_(ကျွဲပွဲ)",
    "Padaung_(ပန်းတောင်း)",
    "Paukkaung_(ပေါက်ခေါင်း)",
    "Paungde_(ပေါင်းတည်)",
    "Pyay_(ပြည်)",
    "Shwedaung_(ရွှေတောင်)",
    "Thegon_(သဲကုန်း)",
    "Innma_(အင်းမ)",
    "Padigone_(ပုတီးကုန်း)",
    "Sinmezwe_(ဆင်မြီးဆွဲ)",
    "Paungdale_(ပေါင်းတလည်)",
    "Gyobingauk_(ကြို့ပင်ကောက်)",
    "Letpadan_(လက်ပတန်းမြို့)",
    "Minhla_(မင်းလှ)",
    "Monyo_(မိုးညို)",
    "Okpho_(အုတ်ဖို)",
    "Tharrawaddy_(သာရ၀တီ)",
    "Nattalin_(နတ်တလင်း)",
    "Zigon_(ဇီးကုန်း)",
    "Thonze_(သုံးဆယ်)",
    "Ooethegone_(အိုးသည်ကုန်း)",
    "Sitkwin_(စစ်ကွင်း)",
    "Tapun_(တာပွန်)",
  ],
  "Sagaing_(စစ်ကိုင်းတိုင်း)": [
    "Hkamti_(ခန္တီး)",
    "Homalin_(ဟုမ္မလင်း)",
    "Leshi_(လေရှီး)",
    "Nanyun_(နန်းယွန်း)",
    "Donhee_(ဒုံဟီး)",
    "Htanparkway_(ထန်ပါခွေ)",
    "Pansaung_(ပန်ဆောင်)",
    "Kanbalu_(ကန့်ဘလူ)",
    "Kyunhla_(ကျွန်းလှ)",
    "Taze_(တန့်ဆည်)",
    "Ye-U_(ရေဦး)",
    "Kale_(ကလေး)",
    "Kalewa_(ကလေးဝ)",
    "Mingin_(မင်းကင်း)",
    "Banmauk_(ဗန်းမောက်)",
    "Indaw_(အင်းတော်)",
    "Katha_(ကသာ)",
    "Kawlin_(ကောလင်)",
    "Pinlebu_(ပင်လည်ဘူး)",
    "Tigyaing_(ထီးချိုင့်)",
    "Wuntho_(ဝန်းသို)",
    "Mawlaik_(မော်လိုက်)",
    "Paungbyin_(ဖေါင်းပြင်)",
    "Ayadaw_(အရာတော်)",
    "Budalin_(ဘုတလင်)",
    "Chaung-U_(ချောင်းဦး)",
    "Monywa_(မုံရွာ)",
    "Myaung_(မြှောင်)",
    "Myinmu_(မြင်းမူ)",
    "Sagaing_(စစ်ကိုင်း)",
    "Khin-U_(ခင်ဦး)",
    "Shwebo_(ရွှေဘို)",
    "Wetlet_(ဝက်လက်)",
    "Tabayin_(ဒီပဲယင်း)",
    "Kyaukmyaung_(ကျောက်မြောင်း)",
    "Tamu_(တမူး)",
    "Khampat_(ခန်းပတ်)",
    "Myothit_(မြို့သစ်)",
    "Kani_(ကနီ)",
    "Pale_(ပုလဲ)",
    "Salingyi_(ဆားလင်းကြီး)",
    "Yinmabin_(ယင်းမာပင်)",
  ],
  "Tanintharyi_(တနင်္သာရီတိုင်း)": [
    "Dawei_(ထားဝယ်)",
    "Launglon_(လောင်းလုံ)",
    "Thayetchaung_(သရက်ချောင်း)",
    "Yebyu_(ရေဖြူ)",
    "Kaleinaung_(ကလိန်အောင်)",
    "Myitta_(မေတ္တာ)",
    "Bokpyin_(ဘုတ်ပြင်း)",
    "Kawthoung_(ကော့သောင်း)",
    "Karathuri_(ကရသူရိ)",
    "Khamaukgyi_(ခမောက်ကြီး)",
    "Pyigyimandaing_(ပြည်ကြီးမဏ္ဍိုင်)",
    "Kyunsu_(ကျွန်းစု)",
    "Myeik_(မြိတ်)",
    "Palaw_(ပုလော)",
    "Palauk_(ပလောက်)",
  ],
  "East_Shan_State_(အရှေ့ရှမ်းပြည်နယ်)": [
    "Kengtung_(ကျိုင်းတုံ)",
    "Mong_Khet_(မိုင်းခတ်)",
    "Mong_La_(မိုင်းလား)",
    "Mong_Yang_(မိုင်းယန်း)",
    "Mine_Pauk_(မိုင်းပေါက်)",
    "Mong_Hpayak_(မိုင်းဖြတ်)",
    "Mong_Yawng_(မိုင်းယောင်း)",
    "Mong_Hsat_(မိုင်းဆတ်)",
    "Mong_Ping_(မိုင်းပြင်း)",
    "Mong_Tong_(မိုင်းတုံ)",
    "Tachileik_(တာချီလိတ်)",
    "Minekoke_(မိုင်းကုတ်)",
    "Ponparkyin_(ပုံပါကျင်)",
  ],
  "North_Shan_State_(ရှမ်းပြည်နယ်မြောက်ပိုင်း)": [
    "Hsipaw_(သီပေါ)",
    "Kyaukme_(ကျောက်မဲ)",
    "Mantong_(မန်တုန်)",
    "Namhsan_(နမ့်ဆန်)",
    "Namtu_(နမ္မတူ)",
    "Nawnghkio_(နောင်ချို)",
    "Hsenwi_(သိန္နီ)",
    "Lashio_(လားရှိုး)",
    "Mongyai_(မိုင်းရယ်)",
    "Tangyan_(တန့်ယန်း)",
    "Laukkaing_(လောက်ကိုင်)",
    "Konkyan_(ကုန်းကြမ်း)",
    "Kutkai_(ကွတ်ခိုင်)",
    "Muse_(မူဆယ်)",
    "Namhkam_(နမ့်ခမ်း)",
    "Hopang_(ဟိုပုန်)",
    "Mongmao_(မိုင်းမော)",
    "Pangwaun_(ပန်ဝိုင်)",
    "Matman_(မက်မန်း)",
    "Pangsang_(ပန်ဆန်း)",
    "Mabein_(မဘိမ်း)",
    "Mongmit_(မိုးမိတ်)",
  ],
  "South_Shan_State_(တောင်ပိုင်းရှမ်းပြည်နယ်)": [
    "Langkho_(လင်းခေး)",
    "Mawkmai_(မောက်မယ်)",
    "Mong Nai_(မိုင်းနိုင်း)",
    "Mong Pan_(မိုင်းပန်)",
    "Kunhing_(ကွန်ဟိန်း)",
    "Kyethi_(ကျေးသီး)",
    "Lai-Hka_(လဲချား)",
    "Loilen_(လွိုင်လင်)",
    "Mong_Hsu_(မိုင်းရှူး)",
    "Mong_Kung_(မိုင်းကိုင်)",
    "Nansang_(နမ့်စန်)",
    "Hopong_(ဟိုပုံး)",
    "Hsi_Hseng_(ဆီဆိုင်)",
    "Kalaw_(ကလော)",
    "Lawksawk_(ရပ်စောက်)",
    "Nyaungshwe_(ညောင်ရွှေ)",
    "Pekon_(ဖယ်ခုံ)",
    "Pingdaya_(ပင်းတယ)",
    "Pinlaung_(ပင်လောင်း)",
    "Taunggyi_(တောင်ကြီး)",
    "Ywangan_(ရှာငံ)",
  ],
  "Kachin_State_(ကချင်ပြည်နယ်)": [
    "Bhamo_(ဗန်းမော်)",
    "Mansi_(မန်စီ)",
    "Momauk_(မိုးမောက်)",
    "Shwegu_(ရွှေကူ)",
    "Hpakant_(ဖားကန့်)",
    "Mogaung_(မိုးကောင်း)",
    "Mohnyin_(မိုးညှင်း)",
    "Chipwi_(ချီဗွေ)",
    "Hsawlaw_(ဆော့လော)",
    "Injangyang_(အင်ဂျန်းယန်)",
    "Myitkyina_(မြစ်ကြီးနားမြို့)",
    "Tanai_(တနိုင်း)",
    "Waingmaw_(ဝိုင်းမော်)",
    "Kawnglanghpu_(ခေါင်လန်ဖူး)",
    "Machanbaw_(မချမ်းဘေ)",
    "Nogmung_(နောင်မွန်း)",
    "Puta-O_(ပူတာအို)",
    "Sumprabum_(ဆွမ်ပရာဘွမ်)",
  ],
  "Kayin_State_(ကရင်ပြည်နယ်)": [
    "Hlaignbwe_(လှိုင်ဘွဲ့)",
    "Hpa-an_(ဘားအံ)",
    "Thandaunggyi_(သံတောင်ကြီး)",
    "Hpapun_(ဖာပွန်)",
    "Kawkareik_(ကော့ကရိတ်)",
    "Kyain Seikgyi_(ကြာအင်းဆိပ်ကြီး)",
    "Myawaddy_(မြဝတီ)",
  ],
  "Mon_State_(မွန်ပြည်နယ်)": [
    "Chaungzon_(ချောင်းဆုံ)",
    "Kyaikmaraw_(ကျိုက်မရော)",
    "Mawlamyine_(မော်လမြိုင်)",
    "Mudon_(မုဒုံ)",
    "Thanbyuzayat_(သံဖြူဇရပ်)",
    "Ye_(ရေး)",
    "Bilin_(ဘီလင်း)",
    "Kyaikto_(ကျိုက်ထို)",
    "Paung_(ပေါင်)",
    "Thaton_(သထုံ)",
  ],
  "Chin_State_(ချင်းပြည်နယ်)": [
    "Falam_(ဖလမ်း)",
    "Tiddim_(တီးတိန်)",
    "Ton_Zang_(တွန်းဇံ)",
    "Hakha_(ဟားခါး)",
    "Htantlang_(ထန်တလန်)",
    "Kanpetlet_(ကန်ပက်လက်)",
    "Matupi_(မတူပီ)",
    "Mindat_(မင်းတပ်)",
    "Paletwa_(ပလက်၀)",
  ],
  "Rakhine_State_(ရခိုင်ပြည်နယ်)": [
    "Ann_(အမ်း)",
    "Kyaukpyu_(ကျောက်ဖြူ)",
    "Manaung_(မာန်အောင်)",
    "Ramree_(ရမ်းဗြဲ)",
    "Buthidaung_(ဘူးသီးတောင်)",
    "Maungdaw_(မောင်တော)",
    "Pauktaw_(ပေါက်တော)",
    "Ponnagyun_(ပုဏ္ဏားကျွန်း)",
    "Rathedaung_(ရသေ့တောင်)",
    "Sittwe_(စစ်တွေ)",
    "Gaw_(ဂေါ)",
    "Thandwe_(သံတွဲ)",
    "Toungup_(တောင်ကုတ်)",
    "Kyauktaw_(ကျောက်တော်)",
    "Minbya_(မင်းပြား)",
    "Mrauk-U_(မြောက်ဦး)",
    "Myebon_(မြေပုံ)",
  ],
  "Kayah_State_(ကယားပြည်နယ်)": [
    "Bawlakhe_(ဘောလခဲ)",
    "Hpasawng_(ဖားဆောင်း)",
    "Mese_(မယ်ဆည်)",
    "Demoso_(ဒီမောဆို)",
    "Hpruso_(ဖရူဆို)",
    "Loikaw_(လွိုင်ကော်)",
    "Shadaw_(ရှားတော)",
  ],
};
